name: Run Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - name: Check out module_dependencies
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        id: restore-cache
        with:
          path: ${{ env.pythonLocation }}
          key: python-dependencies-${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}-${{ env.pythonLocation }}

      - name: Install dependencies on cache miss
        run: |
          pip install --no-cache-dir --upgrade pip
          pip install --no-cache-dir --upgrade --requirement requirements.txt
          pip install --no-cache-dir --upgrade --requirement requirements-dev.txt
        if: steps.restore-cache.outputs.cache-hit != 'true'

      - name: Run test suite
        run: |
          pytest tests
